<?php
/**
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '{nFormatted} B' => '{nFormatted} B',
    '{nFormatted} GB' => '{nFormatted} GB',
    '{nFormatted} GiB' => '{nFormatted} GiB',
    '{nFormatted} kB' => '{nFormatted} kB',
    '{nFormatted} KiB' => '{nFormatted} KiB',
    '{nFormatted} MB' => '{nFormatted} MB',
    '{nFormatted} MiB' => '{nFormatted} MiB',
    '{nFormatted} PB' => '{nFormatted} PB',
    '{nFormatted} PiB' => '{nFormatted} PiB',
    '{nFormatted} TB' => '{nFormatted} TB',
    '{nFormatted} TiB' => '{nFormatted} TiB',
    '{nFormatted} {n, plural, =1{byte} other{bytes}}' => '{nFormatted} {n, plural, one{bayt} few{bayt} many{baytlar} other{bayt}}',
    '{nFormatted} {n, plural, =1{gibibyte} other{gibibytes}}' => '{nFormatted} {n, plural, one{gibibayt} few{gibibayt} many{gibibayt} other{gibibayt}}',
    '{nFormatted} {n, plural, =1{gigabyte} other{gigabytes}}' => '{nFormatted} {n, plural, one{gigabayt} few{gigabayt} many{gigabayt} other{gigabayt}}',
    '{nFormatted} {n, plural, =1{kibibyte} other{kibibytes}}' => '{nFormatted} {n, plural, one{kibibayt} few{kibibayt} many{kibibayt} other{kibibayt}}',
    '{nFormatted} {n, plural, =1{kilobyte} other{kilobytes}}' => '{nFormatted} {n, plural, one{kilobayt} few{kilobayt} many{kilobayt} other{kilobayt}}',
    '{nFormatted} {n, plural, =1{mebibyte} other{mebibytes}}' => '{nFormatted} {n, plural, one{mebibayt} few{mebibayt} many{mebibayt} other{mebibayt}}',
    '{nFormatted} {n, plural, =1{megabyte} other{megabytes}}' => '{nFormatted} {n, plural, one{megabayt} few{megabayt} many{megabayt} other{megabayt}}',
    '{nFormatted} {n, plural, =1{pebibyte} other{pebibytes}}' => '{nFormatted} {n, plural, one{pebibayt} few{pebibayt} many{pebibayt} other{pebibayt}}',
    '{nFormatted} {n, plural, =1{petabyte} other{petabytes}}' => '{nFormatted} {n, plural, one{petabayt} few{petabayt} many{petabayt} other{petabayt}}',
    '{nFormatted} {n, plural, =1{tebibyte} other{tebibytes}}' => '{nFormatted} {n, plural, one{tebibayt} few{tebibayt} many{tebibayt} other{tebibayt}}',
    '{nFormatted} {n, plural, =1{terabyte} other{terabytes}}' => '{nFormatted} {n, plural, one{terabayt} few{terabayt} many{terabayt} other{terabayt}}',
    '(not set)' => '(qiymatlanmagan)',
    'An internal server error occurred.' => 'Сервернинг ички хатолиги юз берди.',
    'Are you sure you want to delete this item?' => 'Сиз ростдан ҳам ушбу элементни ўчирмоқчимисиз?',
    'Delete' => 'Ўчириш',
    'Error' => 'Хато',
    'File upload failed.' => 'Файлни юклаб бўлмади.',
    'Home' => 'Асосий',
    'Invalid data received for parameter "{param}".' => '"{param}" параметр қиймати нотўғри.',
    'Login Required' => 'Кириш талаб қилинади.',
    'Missing required arguments: {params}' => 'Қуйидаги зарур аргументлар мавжуд эмас: {params}',
    'Missing required parameters: {params}' => 'Қуйидаги зарур аргументлар мавжуд эмас: {params}',
    'No' => 'Йўқ',
    'No help for unknown command "{command}".' => '"{command}" ноаниқ команда учун маълумотнома мавжуд эмас.',
    'No help for unknown sub-command "{command}".' => '"{command}" ноаниқ қисм команда учун маълумотнома мавжуд эмас.',
    'No results found.' => 'Ҳеч нима топилмади.',
    'Only files with these MIME types are allowed: {mimeTypes}.' => 'Фақат қуйидаги МИМE-туридаги файлларни юклашга руҳсат берилган: {mimeTypes}.',
    'Only files with these extensions are allowed: {extensions}.' => 'Фақат қуйидаги кенгайтмали файлларни юклашга руҳсат берилган: {extensions}.',
    'Page not found.' => 'Саҳифа топилмади.',
    'Please fix the following errors:' => 'Навбатдаги хатоликларни тўғриланг:',
    'Please upload a file.' => 'Файлни юкланг.',
    'Showing <b>{begin, number}-{end, number}</b> of <b>{totalCount, number}</b> {totalCount, plural, one{item} other{items}}.' => 'Намойиш этилаябди <b>{begin, number}-{end, number}</b> та ёзув <b>{totalCount, number}</b> тадан.',
    'The file "{file}" is not an image.' => '«{file}» файл расм эмас.',
    'The file "{file}" is too big. Its size cannot exceed {formattedLimit}.' => '«{file}» файл жуда катта. Ўлчам {formattedLimit} ошиши керак эмас.',
    'The file "{file}" is too small. Its size cannot be smaller than {formattedLimit}.' => '«{file}» файл жуда кичкина. Ўлчам {formattedLimit} кам бўлмаслиги керак.',
    'The format of {attribute} is invalid.' => '«{attribute}» қийматнинг формати нотўғри.',
    'The image "{file}" is too large. The height cannot be larger than {limit, number} {limit, plural, one{pixel} other{pixels}}.' => '«{file}» файл жуда катта. Баландлик {limit, number} {limit, plural, one{pikseldan} few{pikseldan} many{pikseldan} other{pikseldan}} ошмаслиги керак.',
    'The image "{file}" is too large. The width cannot be larger than {limit, number} {limit, plural, one{pixel} other{pixels}}.' => '«{file}» файл жуда катта. Эни {limit, number} {limit, plural, one{pikseldan} few{pikseldan} many{pikseldan} other{pikseldan}} ошмаслиги керак.',
    'The image "{file}" is too small. The height cannot be smaller than {limit, number} {limit, plural, one{pixel} other{pixels}}.' => '«{file}» файл жуда кичкина. Баландлик {limit, number} {limit, plural, one{pikseldan} few{pikseldan} many{pikseldan} other{pikseldan}} кам бўлмаслиги керак.',
    'The image "{file}" is too small. The width cannot be smaller than {limit, number} {limit, plural, one{pixel} other{pixels}}.' => '«{file}» жуда кичкина. Эни {limit, number} {limit, plural, one{pikseldan} few{pikseldan} many{pikseldan} other{pikseldan}} кам бўлмаслиги керак.',
    'The requested view "{name}" was not found.' => 'Сўралаётган "{name}" намойиш файли топилмади.',
    'The verification code is incorrect.' => 'Текширув коди нотўғри.',
    'Total <b>{count, number}</b> {count, plural, one{item} other{items}}.' => 'Жами <b>{count, number}</b> {count, plural, one{yozuv} few{yozuv} many{yozuv} other{yozuv}}.',
    'Unable to verify your data submission.' => 'Юборилган маълумотларни текшириб бўлмади.',
    'Unknown command "{command}".' => '"{command}" ноаниқ команда.',
    'Unknown option: --{name}' => 'Ноаниқ опсия: --{name}',
    'Update' => 'Таҳрирлаш',
    'View' => 'Кўриш',
    'Yes' => 'Ҳа',
    'You are not allowed to perform this action.' => 'Сизга ушбу амални бажаришга руҳсат берилмаган.',
    'You can upload at most {limit, number} {limit, plural, one{file} other{files}}.' => 'Сиз {limit, number} {limit, plural, one{fayldan} few{fayllardan} many{fayllardan} other{fayllardan}} кўпини юклаб ола олмайсиз.',
    'in {delta, plural, =1{a day} other{# days}}' => '{delta, plural, =1{kundan} one{# kundan} few{# kundan} many{# kunlardan} other{# kundan}} keyin',
    'in {delta, plural, =1{a minute} other{# minutes}}' => '{delta, plural, =1{minutdan} one{# minutdan} few{# minutlardan} many{# minutdan} other{# minutlardan}} keyin',
    'in {delta, plural, =1{a month} other{# months}}' => '{delta, plural, =1{oydan} one{# oydan} few{# oydan} many{# oylardan} other{# oylardan}} keyin',
    'in {delta, plural, =1{a second} other{# seconds}}' => '{delta, plural, =1{sekunddan} one{# sekunddan} few{# sekundlardan} many{# sekunddan} other{# sekundlardan}} keyin',
    'in {delta, plural, =1{a year} other{# years}}' => '{delta, plural, =1{yildan} one{# yildan} few{# yillardan} many{# yillardan} other{# yillardan}} keyin',
    'in {delta, plural, =1{an hour} other{# hours}}' => '{delta, plural, =1{soatdan} one{# soatdan} few{# soatlardan} many{# soatlardan} other{# soatlardan}} keyin',
    'just now' => 'хозироқ',
    'the input value' => 'киритилган қиймат',
    '{attribute} "{value}" has already been taken.' => '{attribute} «{value}» аввалроқ банд қилинган.',
    '{attribute} cannot be blank.' => '«{attribute}» тўлдириш шарт.',
    '{attribute} is invalid.' => '«{attribute}» қиймати нотўғри.',
    '{attribute} is not a valid URL.' => '«{attribute}» қиймати тўғри УРЛ эмас.',
    '{attribute} is not a valid email address.' => '«{attribute}» қиймати тўғри эмаил манзил эмас.',
    '{attribute} must be "{requiredValue}".' => '«{attribute}» қиймати «{requiredValue}» га тенг бўлиши керак.',
    '{attribute} must be a number.' => '«{attribute}» қиймати сон бўлиши керак.',
    '{attribute} must be a string.' => '«{attribute}» қиймати сатр бўлиши керак.',
    '{attribute} must be an integer.' => '«{attribute}» қиймати бутун сон бўлиши керак.',
    '{attribute} must be either "{true}" or "{false}".' => '«{attribute}» қиймати «{true}» ёки «{false}» бўлиши керак.',
    '{attribute} must be greater than "{compareValue}".' => '«{attribute}» қиймати «{compareValue}» дан катта бўлиши керак.',
    '{attribute} must be greater than or equal to "{compareValue}".' => '«{attribute}» қиймати «{compareValue}» дан катта ёки тенг бўлиши керак.',
    '{attribute} must be less than "{compareValue}".' => '«{attribute}» қиймати «{compareValue}» дан кичкина бўлиши керак.',
    '{attribute} must be less than or equal to "{compareValue}".' => '«{attribute}» қиймати «{compareValue}» дан кичик ёки тенг бўлиши керак.',
    '{attribute} must be no greater than {max}.' => '«{attribute}» қиймати {max} дан ошмаслиги керак.',
    '{attribute} must be no less than {min}.' => '«{attribute}» қиймати {min} дан кичкина бўлмаслиги керак.',
    '{attribute} must be repeated exactly.' => '«{attribute}» қиймати бир хил тарзда такрорланиши керак.',
    '{attribute} must not be equal to "{compareValue}".' => '«{attribute}» қиймати «{compareValue}» га тенг бўлмаслиги керак.',
    '{attribute} must not be equal to "{compareValueOrAttribute}".' => '«{attribute}» қиймати «{compareValueOrAttribute}» қийматига тенг бўлмаслиги лозим.',
    '{attribute} should contain at least {min, number} {min, plural, one{character} other{characters}}.' => '«{attribute}» қиймати минимум {min, number} {min, plural, one{belgidan} few{belgidan} many{belgidan} other{belgidan}} ташкил топиши керак.',
    '{attribute} should contain at most {max, number} {max, plural, one{character} other{characters}}.' => '«{attribute}» қиймати максимум {max, number} {max, plural, one{belgidan} few{belgidan} many{belgidan} other{belgidan}} ошмаслиги керак.',
    '{attribute} should contain {length, number} {length, plural, one{character} other{characters}}.' => '«{attribute}» қиймати {length, number} {length, plural, one{belgidan} few{belgidan} many{belgidan} other{belgidan}} tashkil topishi kerak.',
    '{delta, plural, =1{a day} other{# days}} ago' => '{delta, plural, =1{kun} one{kun} few{# kun} many{# kun} other{# kun}} аввал',
    '{delta, plural, =1{a minute} other{# minutes}} ago' => '{delta, plural, =1{daqiqa} one{# daqiqa} few{# daqiqa} many{# daqiqa} other{# daqiqa}} аввал',
    '{delta, plural, =1{a month} other{# months}} ago' => '{delta, plural, =1{oy} one{# oy} few{# oy} many{# oy} other{# oy}} аввал',
    '{delta, plural, =1{a second} other{# seconds}} ago' => '{delta, plural, =1{soniya} one{# soniya} few{# soniya} many{# soniya} other{# soniya}} аввал',
    '{delta, plural, =1{a year} other{# years}} ago' => '{delta, plural, =1{yil} one{# yil} few{# yil} many{# yil} other{# yil}} аввал',
    '{delta, plural, =1{an hour} other{# hours}} ago' => '{delta, plural, =1{soat} one{# soat} few{# soat} many{# soat} other{# soat}} аввал',
];
